defaults:
  - base_model_config

name: LLaMA3-8b-Instruct
model_type: instruct
configs:
  model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
  max_seq_len: 4096
  system_prompt:
  max_new_tokens: 32
