defaults:
  - base_decoder_config

name: ActivationDecoding
method: ActivationDecoding
configs:
  post_softmax: True
  dola_layers: null
  alpha: 0.5
  decoding_strategy: entropy
  decoding_mode: activation
  info_layer: 24
  relative_top: 0.1