defaults:
  - base_decoder_config

name: BaselineMaskedHallucinationHead
method: baseline_masked_hallucination_head
configs:
  hallucination_heads_dir: ./hallucination_heads/
  num_hallucination_heads: 10
  feature_names:
    - BOS
    - Instruction
    - ICL Demonstration
    - Contexts
    - Question
    - Answer Prefix
    - New Tokens
  aggregation_method: mean
