defaults:
  - base_decoder_config

name: DeCoReEntropyAmateur
method: DeCoReEntropy
configs:
  retrieval_heads_dir: ./retrieval_heads/
  num_retrieval_heads: 50
  post_softmax: True
  alpha_cap: null
  scale_alpha: False
  amateur_model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct