defaults:
  - base_decoder_config

name: DeCoReWasserstein
method: decore_wasserstein
configs:
  retrieval_heads_dir: ./retrieval_heads/
  num_retrieval_heads: 50
  post_softmax: True
  alpha_cap: null
  scale_alpha: False