defaults:
  - base_decoder_config

name: DeCoReEntropy
method: decore_entropy
configs:
  retrieval_heads_dir: ./retrieval_heads/
  num_retrieval_heads: 50
  post_softmax: True
  alpha_cap: null
  scale_alpha: False
  amateur_model_name_or_path: null