defaults:
  - base_decoder_config

name: DeCoReGuided
method: decore_guided
configs:
  retrieval_heads_dir: ./retrieval_heads/
  num_retrieval_heads: 50
  classifier_path: ./guiding_classifier/nq__lr_l2__seqlen_4.pt
  classifier_max_sequence_length: 4
  classifier_num_samples: 4
  post_softmax: False